format_version: 10
pipelines:
 prometheus:
    group: tools
    label_template: ${COUNT}
    materials:
      ansible:
        git: https://github.com/NARENDRA935/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]
                    workingdir: prometheus
                - exec:
                    command: terraform
                    arguments: ["apply","-auto-approve"]
                    workingdir: prometheus


